export type GetDoctorsDto = {
  specialityId?: number;
  city?: string;
  area?: string;
  page?: number;
  symptomId?: number;
  serviceId?: number;
  diseaseId?: number;
  minFee?: number;
  maxFee?: number;
  gender?: "male" | "female" | "all";
  isFree?: boolean;
  lat?: number;
  lng?: number;
  consultationType?: number;
  sortBy?: "fee" | "experience";
  sortDirection?: "ASC" | "DESC";
  availableToday?: boolean;
  hospitalId?: number;
};
