// @ts-nocheck
import {
  mysqlTable,
  int,
  bigint,
  float,
  double,
  tinyint,
  smallint,
  boolean,
  varchar,
  text,
  longtext,
  date,
  time,
  timestamp,
  datetime,
  json,
  decimal,
} from "drizzle-orm/mysql-core";

export const patientAppointments = mysqlTable("patient_appointments", {
  id: bigint("id", { mode: "bigint" }).primaryKey(),
  doctorHospitalId: int("doctor_hospital_id").notNull().default(0),
  specialityId: int("speciality_id").notNull().default(0),
  doctorId: int("dID").notNull().default(0),
  doctorName: varchar("doctor_name", { length: 255 }),
  doctorPhone: varchar("doctor_phone", { length: 100 }),
  hospitalId: int("hospitalID").notNull().default(0),
  fee: int("fee").notNull().default(0),
  promoCodeId: bigint("promo_code_id", { mode: "bigint", unsigned: true }),
  notes: longtext("notes"),
  userId: int("user_id").notNull().default(0),
  patientName: varchar("patient_name", { length: 255 }),
  patientPhone: varchar("patient_phone", { length: 100 }),
  patientAge: float("patient_age").notNull().default(0),
  date: date("date"),
  time: time("time"),
  token: int("token").notNull().default(0),
  day: int("day").notNull().default(0),
  month: int("month").notNull().default(0),
  year: int("year").notNull().default(0),
  hospitalName: varchar("hospital_name", { length: 255 }),
  patientId: int("patientID").notNull().default(0),
  approved: tinyint("approved").notNull().default(0),
  extra: tinyint("extra").notNull().default(0),
  cancelled: tinyint("cancelled").notNull().default(0),
  timePassed: tinyint("time_passed").notNull().default(0),
  prescriptionAdded: tinyint("prescription_added").notNull().default(0),
  prescriptionAddedFrom: tinyint("prescription_added_from").notNull().default(0),
  cancelledByDoctor: tinyint("cancelled_by_doctor").notNull().default(0),
  cancelledByPatient: tinyint("cancelled_by_patient").notNull().default(0),
  paymentReceived: tinyint("payment_received").notNull().default(0),
  consultantNotes: longtext("patient_appointment_consultant_notes"),
  consultantPlan: longtext("patient_appointment_consultant_plan"),
  investigationNotes: longtext("patient_appointment_investigation_notes"),
  historyNotes: longtext("patient_appointment_history_notes"),
  treatmentPlan: longtext("patient_appointment_treatment_plan"),
  tests: longtext("patient_appointment_tests"),
  instructions: longtext("patient_appointment_instructions"),
  onlineAppointment: tinyint("online_appointment").notNull().default(0),
  departmentId: int("department_id").notNull().default(0),
  title: varchar("patient_appointment_title", { length: 255 }),
  bloodPressure: varchar("patient_appointment_blood_pressure", { length: 50 }),
  bloodSugar: float("patient_appointment_blood_sugar").notNull().default(0),
  height: float("patient_appointment_height").notNull().default(0),
  weight: float("patient_appointment_weight").notNull().default(0),
  patientSurgeries: varchar("patient_surgeries", { length: 255 }),
  patientMedications: varchar("patient_medications", { length: 255 }),
  patientConditions: varchar("patient_conditions", { length: 255 }),
  temperature: varchar("patient_appointment_temperature", { length: 100 }),
  heartRate: varchar("patient_appointment_heart_rate", { length: 100 }),
  spo2: varchar("patient_appointment_spo2", { length: 100 }),
  pefr: varchar("patient_appointment_pefr", { length: 100 }),
  ent: varchar("patient_appointment_ent", { length: 100 }),
  chest: varchar("patient_appointment_chest", { length: 100 }),
  patientCity: varchar("patient_city", { length: 100 }),
  patientArea: varchar("patient_area", { length: 100 }),
  patientDisease: varchar("patient_disease", { length: 100 }),
  patientBmi: varchar("patient_bmi", { length: 255 }),
  patientPreferredWayOfWeightloss: varchar("patient_preferred_way_of_weightloss", { length: 255 }),
  patientDesiredWeightLoss: varchar("patient_desired_weight_loss", { length: 255 }),
  patientTimeToLoseWeight: varchar("patient_time_to_lose_weight", { length: 255 }),
  patientOccupation: varchar("patient_occupation", { length: 255 }),
  patientMaritalStatus: varchar("patient_marital_status", { length: 255 }),
  patientPersonalHistory: longtext("patient_personal_history"),
  patientSystematicHistory: longtext("patient_systematic_history"),
  patientSurgicalHistory: longtext("patient_surgical_history"),
  patientGyneAndObsHistory: longtext("patient_gyne_and_obs_history"),
  patientWeightlossOptionsTriedInPast: varchar("patient_weightloss_options_tried_in_past", { length: 255 }),
  patientWeightlossOptionsTriedInPastOther: longtext("patient_weightloss_options_tried_in_past_other"),
  patientEverAllergicToMedications: tinyint("patient_ever_allergic_to_medications"),
  patientEverAllergicToMedicationsOther: longtext("patient_ever_allergic_to_medications_other"),
  patientForWhichYouStruggle: varchar("patient_for_which_you_struggle", { length: 255 }),
  patientForWhichYouStruggleOther: longtext("patient_for_which_you_struggle_other"),
  patientInterestedInMedications: tinyint("patient_interested_in_medications"),
  patientInterestedInMedicationsOther: longtext("patient_interested_in_medications_other"),
  flApptId: int("fl_appt_id").notNull().default(0),
  appointmentProbability: int("appointment_probability").notNull().default(2),
  appointmentStatus: int("appointment_status").notNull().default(0),
  appointmentSubStatus: int("appointment_sub_status").notNull().default(0),
  messageToPatient: tinyint("message_to_patient").notNull().default(0),
  messageToDoctor: tinyint("message_to_doctor").notNull().default(0),
  messageToAssistant: tinyint("message_to_assistant").notNull().default(0),
  voiceMessageToPatient: tinyint("voice_message_to_patient").notNull().default(0),
  referralAmount: float("referral_amount").notNull().default(0),
  doctorReferralAmount: int("doctor_referral_amount").notNull().default(0),
  consultancyReferral: int("consultancy_referral").notNull().default(0),
  consultancyFeeReferralOn: int("consultancy_fee_referral_on").notNull().default(1),
  doctorFee: int("doctor_fee").notNull().default(0),
  doctorFeeAfterHospitalShare: int("doctor_fee_after_hospital_share").notNull().default(0),
  referredSharePercentage: int("referred_share_percentage").notNull().default(0),
  referredShareAmount: int("referred_share_amount").notNull().default(0),
  referredSpecialityId: int("referred_speciality_id").notNull().default(0),
  correctedReferralAmount: decimal("corrected_referral_amount").notNull().default(0),
  walletAmount: int("wallet_amount").notNull().default(0),
  walletAmountDetail: json("wallet_amount_detail"),
  discount: float("discount").notNull().default(0),
  discountPercentage: int("discount_percentage").notNull().default(0),
  followUp: tinyint("follow_up").notNull().default(0),
  followUpFor: bigint("follow_up_for", { mode: "bigint" }).notNull().default(0),
  appointmentType: tinyint("appointment_type").notNull().default(1),
  awayFromCity: tinyint("away_from_city").notNull().default(0),
  paymentId: int("payment_id").notNull().default(0),
  paymentEvidence: varchar("payment_evidence", { length: 255 }),
  paymentMethodId: int("payment_method_id").notNull().default(0),
  paidToDoctor: tinyint("paid_to_doctor").notNull().default(0),
  appType: tinyint("app_type").notNull().default(0),
  deviceType: tinyint("device_type").notNull().default(0),
  accessToken: varchar("access_token", { length: 255 }),
  reviewedAt: timestamp("reviewed_at"),
  paymentStatus: int("payment_status").notNull().default(1),
  harmonyStatus: int("harmony_status").notNull().default(1),
  callCenterAudioUrl: varchar("call_center_audio_url", { length: 150 }),
  callCenterNotes: text("call_center_notes"),
  isProcedure: tinyint("is_procedure").notNull().default(0),
  recordExists: tinyint("record_exists").notNull().default(0),
  isFree: tinyint("is_free").notNull().default(0),
  isDialer: tinyint("is_dialer").notNull().default(0),
  isDirectBooking: tinyint("is_direct_booking").notNull().default(0),
  isReferred: tinyint("is_referred").notNull().default(0),
  updatedBy: int("last_update_by_user_id").default(0),
  addedBy: int("added_by").notNull().default(0),
  referredBy: int("referred_by").default(0),
  referredFrom: int("referred_from").notNull().default(0),
  referredTo: int("referred_to").default(0),
  leadSourceId: int("lead_source_id").default(0),
  corporateId: int("corporate_id").default(0),
  corporatePaymentMode: tinyint("corporate_payment_mode").default(0),
  isAgentSpecial: tinyint("is_agent_special").notNull().default(0),
  contractType: tinyint("contract_type").default(1),
  isPersonalAppointment: tinyint("is_personal_appointment").default(0),
  isPromotionAvailable: tinyint("is_promotion_available").default(0),
  isPromotional: tinyint("is_promotional").default(0),
  promotionalFor: bigint("promotional_for", { mode: "bigint" }).default(0),
  isCallMyDoctor: tinyint("is_call_my_doctor").default(0),
  isCommutable: tinyint("is_commutable").default(1),
  assignedTo: int("assigned_to").notNull().default(0),
  inProcessScheduleAssign: int("in_process_schedule_assign").notNull().default(0),
  scheduleShowedupAssign: int("schedule_showedup_assign").notNull().default(0),
  isMarhamAppointment: tinyint("is_marham_appointment").default(1),
  appointmentUserType: tinyint("appointment_user_type").default(4),
  uuid: varchar("uuid", { length: 50 }),
  visitorSource: varchar("visitor_source", { length: 50 }),
  utmSource: varchar("utm_source", { length: 255 }),
  utmMedium: varchar("utm_medium", { length: 255 }),
  utmCampaign: varchar("utm_campaign", { length: 255 }),
  ipAddress: varchar("ip_address", { length: 50 }),
  onlinePayment: tinyint("online_payment").default(0),
  paymentTimestamps: json("payment_timestamps"),
  cancelledAssignTo: int("cancelled_assign_to"),
  isRocheAppointment: tinyint("is_roche_appointment").notNull().default(0),
  harmonyAssignTo: int("harmony_assign_to"),
  ocContractedHospitalId: int("oc_contracted_hospital_id").notNull().default(0),
  walletTransactionId: int("wallet_transaction_id").notNull().default(0),
  subscriptionId: int("subscription_id"),
  subscriptionBatchId: int("subscription_batch_id"),
  onlineClinicId: int("online_clinic_id"),
  evidenceTransactionId: varchar("evidence_transaction_id", { length: 255 }),
  evidenceAmount: double("evidence_amount"),
  evidencePaymentDate: date("evidence_payment_date"),
  moengageUuid: varchar("moengage_uuid", { length: 50 }),
  scheduledAt: timestamp("scheduled_at"),
  cancelledAssignAt: datetime("cancelled_assign_at"),
  cancelledAt: datetime("cancelled_at"),
  harmonyAssignAt: timestamp("harmony_assign_at"),
  showedupAt: timestamp("showedup_at"),
  createdAt: timestamp("created_at").notNull(),
  createdDate: date("created_date"),
  updatedAt: timestamp("updated_at"),
});
