// @ts-nocheck
import {
  mysqlTable,
  int,
  bigint,
  float,
  double,
  tinyint,
  smallint,
  boolean,
  varchar,
  text,
  longtext,
  date,
  time,
  timestamp,
  datetime,
  json,
  decimal,
} from "drizzle-orm/mysql-core";

export const corporateUsers = mysqlTable("corporate_users", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("user_id").notNull().default(0),
  corporateId: varchar("corporate_id", { length: 255 }).notNull().default("0"),
  code: varchar("code", { length: 255 }),
  department: varchar("department", { length: 255 }),
  designation: varchar("designation", { length: 255 }),
  paymentMode: varchar("payment_mode", { length: 255 }).notNull().default("0"),
  bookingProcess: varchar("booking_process", { length: 255 }).notNull().default("0"),
  appointment: varchar("appointment", { length: 255 }).notNull().default("0"),
  appointmentDiscountPercentage: varchar("appointment_discount_percentage", { length: 255 }).notNull().default("0"),
  videoConsultation: varchar("video_consultation", { length: 255 }).notNull().default("0"),
  videoConsultationDiscountPercentage: varchar("video_consultation_discount_percentage", { length: 255 }).notNull().default("0"),
  callNow: varchar("call_now", { length: 255 }).notNull().default("0"),
  callNowDiscountPercentage: varchar("call_now_discount_percentage", { length: 255 }).notNull().default("0"),
  labPortal: varchar("lab_portal", { length: 255 }).notNull().default("0"),
  labPortalDiscountPercentage: varchar("lab_portal_discount_percentage", { length: 255 }).notNull().default("0"),
  medicinePortal: varchar("medicine_portal", { length: 255 }).notNull().default("0"),
  medicinePortalDiscountPercentage: varchar("medicine_portal_discount_percentage", { length: 255 }).notNull().default("0"),
  surgery: varchar("surgery", { length: 255 }).notNull().default("0"),
  surgeryDiscountPercentage: varchar("surgery_discount_percentage", { length: 255 }).notNull().default("0"),
  hospital: varchar("hospital", { length: 255 }).notNull().default("0"),
  hospitalDiscountPercentage: varchar("hospital_discount_percentage", { length: 255 }).notNull().default("0"),
  maxLimit: float("max_limit").notNull().default(0),
  opdMaxLimit: varchar("opd_max_limit", { length: 255 }).notNull().default("0"),
  corporatePackageId: varchar("corporate_package_id", { length: 255 }).notNull().default("0"),
  isSubscriptionMode: varchar("is_subscription_mode", { length: 255 }).notNull().default("0"),
  isActive: varchar("is_active", { length: 255 }).notNull().default("0"),
  remainingConsultations: varchar("remaining_consultations", { length: 255 }).notNull().default("0"),
  noOfConsultations: varchar("no_of_consultations", { length: 255 }).notNull().default("0"),
  packageName: varchar("package_name", { length: 255 }),
  insuranceCode: varchar("insurance_code", { length: 255 }),
  updatedBy: varchar("updated_by", { length: 255 }).notNull().default("0"),
  createdAt: timestamp("created_at").notNull(),
  updatedAt: timestamp("updated_at"),
  deletedAt: timestamp("deleted_at"),
});
