// @ts-nocheck
import {
  mysqlTable,
  int,
  bigint,
  float,
  double,
  tinyint,
  smallint,
  boolean,
  varchar,
  text,
  longtext,
  date,
  time,
  timestamp,
  datetime,
  json,
  decimal,
} from "drizzle-orm/mysql-core";

export const diseases = mysqlTable("diseases", {
  id: int("id").autoincrement().primaryKey(),
  disease: varchar("disease", { length: 255 }),
  detail: varchar("detail", { length: 255 }),
  spId: varchar("spID", { length: 255 }).notNull().default("0"),
  speciality: varchar("speciality", { length: 255 }),
  diseaseSoundex: varchar("diseaseSoundex", { length: 255 }),
  dId: varchar("dID", { length: 255 }).notNull().default("0"),
  priority: float("priority").notNull().default(0),
  pageH1: varchar("page_h1", { length: 255 }),
  listingH1: varchar("listing_h1", { length: 255 }),
  pageTitle: varchar("page_title", { length: 255 }),
  listingTitle: varchar("listing_title", { length: 255 }),
  pageMetaDescription: varchar("page_meta_description", { length: 255 }),
  listingMetaDescription: varchar("listing_meta_description", { length: 400 }),
  pageDescriptionUrdu: longtext("page_description_urdu"),
  pageDescriptionEnglish: longtext("page_description_english"),
  slug: longtext("slug"),
  video: varchar("video", { length: 255 }),
  symptoms: longtext("symptoms"),
  causes: longtext("causes"),
  riskFactors: longtext("risk_factors"),
  preventiveMeasures: longtext("preventive_measures"),
  types: longtext("types"),
  pageFaqs: json("page_faqs"),
  diagnosis: longtext("diagnosis"),
  treatment: longtext("treatment"),
  complication: longtext("complication"),
  medicalCheck: longtext("medical_check"),
  expertAdvice: longtext("expert_advice"),
  disclaimer: longtext("disclaimer"),
  image: varchar("image", { length: 255 }),
  urduName: varchar("urdu_name", { length: 255 }),
  createdAt: timestamp("created_at").notNull(),
  updatedAt: timestamp("updated_at"),
});
