// @ts-nocheck
import {
  mysqlTable,
  int,
  bigint,
  float,
  double,
  tinyint,
  smallint,
  boolean,
  varchar,
  text,
  longtext,
  date,
  time,
  timestamp,
  datetime,
  json,
  decimal,
} from "drizzle-orm/mysql-core";

export const doctors = mysqlTable("docdetails", {
  id: int("dlID").autoincrement().primaryKey(),
  name: varchar("docName", { length: 255 }),
  email: varchar("docEmail", { length: 255 }),
  phone: varchar("docPhone", { length: 30 }),
  details: text("docDetails"),
  aboutMe: longtext("aboutMe"),
  degree: varchar("docDegree", { length: 500 }),
  experience: float("docExp"),
  profilePic: varchar("docPic", { length: 255 }),
  categoryId: varchar("catID", { length: 255 }),
  specialityId: varchar("spID", { length: 255 }).notNull(),
  subSpecialityId: varchar("subspID", { length: 255 }).notNull(),
  physician: tinyint("physician"),
  surgen: tinyint("surgen"),
  reviewId: varchar("reviewID", { length: 255 }),
  available: tinyint("available").notNull().default(1),
  relief: varchar("relief", { length: 255 }).notNull().default("0"),
  marham: varchar("marham", { length: 255 }).notNull().default("0"),
  ranking: float("ranking").notNull().default(0),
  pmdc: varchar("pmdc", { length: 100 }),
  gender: tinyint("gender"),
  title: varchar("title", { length: 255 }),
  interview: varchar("interview", { length: 255 }),
  willingForVideoConsultancy: tinyint("willing_for_video_consultancy").notNull().default(0),
  homeService: tinyint("home_service").notNull().default(0),
  videoConsultation: tinyint("video_consultation").notNull().default(0),
  points: float("points").notNull().default(0),
  marhamSpecial: float("marham_special").notNull().default(0),
  marhamSpecial2: double("marham_special_2").notNull().default(0),
  newPoints: float("new_points").notNull().default(1000),
  ra2Points: double("ra_2_points").notNull().default(0),
  appointmentNumber: varchar("appointment_number", { length: 50 }),
  appointmentInstructions: text("appointment_instructions"),
  onlineConsultationInstructions: text("online_consultation_instructions"),
  fixFee: tinyint("fix_fee").notNull().default(0),
  appointmentsBooked: varchar("appointments_booked", { length: 255 }).notNull().default("0"),
  proceduresBooked: varchar("procedures_booked", { length: 255 }).notNull().default("0"),
  profileViews: varchar("profile_views", { length: 255 }).notNull().default("1288"),
  areaOfInterest: longtext("area_of_interest"),
  markedRed: tinyint("marked_red").default(0),
  authToken: varchar("auth_token", { length: 50 }),
  canonicalAt: varchar("canonical_at", { length: 255 }),
  onPanel: tinyint("on_panel").notNull().default(0),
  onPanelAt: timestamp("on_panel_at"),
  offPanelAt: timestamp("off_panel_at"),
  onPanelByUserId: varchar("on_panel_by_user_id", { length: 255 }).default("0"),
  offPanelBy: varchar("off_panel_by", { length: 255 }).default("0"),
  salesNotes: text("sales_notes"),
  profileNotCompleted: tinyint("profile_not_completed").notNull().default(0),
  directBooking: tinyint("direct_booking").notNull().default(0),
  noDirectBooking: tinyint("no_direct_booking").notNull(),
  directBookingNotes: varchar("direct_booking_notes", { length: 500 }),
  addedByUserId: varchar("added_by_user_id", { length: 255 }).notNull().default("0"),
  onLeave: tinyint("on_leave").notNull().default(0),
  onLeaveFrom: date("on_leave_from"),
  onLeaveTo: date("on_leave_to"),
  completionLevel: tinyint("completion_level").default(5),
  profileSelfCompletionLevel: tinyint("profile_self_completion_level").default(0),
  acknowledged: tinyint("acknowledged").default(0),
  acknowledgement: varchar("acknowledgement", { length: 255 }),
  acknowledgedFrom: tinyint("acknowledged_from").default(0),
  rating: double("rating").default(0),
  firstComeFirstServe: tinyint("first_come_first_serve").default(0),
  isRocheDoctor: tinyint("is_roche_doctor").notNull().default(0),
  averageWaitingTime: varchar("average_waiting_time", { length: 50 }),
  averageAppointmentTime: varchar("average_appointment_time", { length: 50 }),
  diagnosisScore: varchar("diagnosis_score", { length: 255 }).default("0"),
  staffScore: varchar("staff_score", { length: 255 }).default("0"),
  bankName: varchar("bank_name", { length: 255 }),
  bankAccountNumber: varchar("bank_account_no", { length: 255 }),
  bankAccountTitle: varchar("bank_account_title", { length: 255 }),
  partnershipCompanyId: varchar("partnership_company_id", { length: 255 }).default("0"),
  hiddenBy: varchar("hidden_by", { length: 255 }).default("0"),
  activeAt: timestamp("active_at"),
  inactiveAt: timestamp("inactive_at"),
  isInactiveByNonPayment: tinyint("is_inactive_by_non_payment").notNull().default(0),
  hiddenAt: timestamp("hidden_at"),
  isVerified: tinyint("is_verified").notNull().default(0),
  onboardingPaymentStatus: tinyint("onboarding_payment_status").notNull().default(3),
  onboardingStatus: varchar("onboarding_status", { length: 255 }),
  ocPoints: float("oc_points").notNull().default(0),
  consultationSpecial: float("consultation_special").notNull().default(0),
  consultationCity: varchar("consultation_city", { length: 100 }),
  callMyDoctor: tinyint("call_my_doctor").default(0),
  accountManagerId: varchar("account_manager_id", { length: 255 }).default("0"),
  actions: json("actions"),
  isPatientChatEnabled: tinyint("is_patient_chat_enabled").default(1),
  isPatientReportSharingEnabled: tinyint("is_patient_report_sharing_enabled").default(1),
  doctorRankingCategoryId: varchar("doctor_ranking_category_id", { length: 255 }).notNull().default("0"),
  maxMonthlyImpressions: varchar("max_monthly_impressions", { length: 255 }).notNull().default("0"),
  maxDailyImpressions: varchar("max_daily_impressions", { length: 255 }).notNull().default("0"),
  maxMonthlyProfileViews: varchar("max_monthly_profile_views", { length: 255 }).notNull().default("0"),
  maxDailyProfileViews: varchar("max_daily_profile_views", { length: 255 }).notNull().default("0"),
  impressionCountLast30Days: bigint("impression_count_last_30_days", { mode: "bigint", unsigned: true }).notNull().default(0),
  forumLikesCount: bigint("forum_likes_count", { mode: "bigint", unsigned: true }).notNull().default(0),
  seo: json("seo"),
  odooId: varchar("odoo_id", { length: 255 }),
  odooUpdatedAt: timestamp("odoo_updated_at"),
  publishedBy: varchar("published_by", { length: 255 }).notNull().default("0"),
  unpublishedBy: varchar("unpublished_by", { length: 255 }).notNull().default("0"),
  isScrapped: tinyint("is_scrapped").default(0),
  dateOfExperience: date("date_of_experience"),
  createdAt: timestamp("createdDate").notNull(),
  updatedAt: timestamp("updated_at"),
  isInHouseDoctor: tinyint("isInHouseDoctor").default(0),
});
