// @ts-nocheck
import {
  mysqlTable,
  int,
  bigint,
  float,
  double,
  tinyint,
  smallint,
  boolean,
  varchar,
  text,
  longtext,
  date,
  time,
  timestamp,
  datetime,
  json,
  decimal,
} from "drizzle-orm/mysql-core";

export const doctorListings = mysqlTable("doclisting", {
  id: int("id").autoincrement().primaryKey(),
  doctorId: varchar("dlID", { length: 255 }).notNull().default("0"),
  doctorName: varchar("docName", { length: 255 }),
  profilePic: varchar("docPic", { length: 255 }),
  hospitalPic: varchar("hospitalPic", { length: 255 }),
  experience: float("docExp").default(0),
  fee: float("docFee").default(0),
  discountFee: float("discountFee").default(0),
  doctorGenderString: varchar("docGender", { length: 255 }),
  categoryId: varchar("catID", { length: 255 }).default("0"),
  categoryName: varchar("catName", { length: 255 }),
  specialityId2: varchar("spID", { length: 255 }).notNull().default("0"),
  subSpecialityId: varchar("subspID", { length: 255 }).notNull().default("0"),
  specialityId: varchar("speciality_id", { length: 255 }).notNull().default("0"),
  speciality: varchar("speciality", { length: 255 }),
  subSpeciality: varchar("subSpeciality", { length: 255 }),
  specialityName: varchar("speciality_name", { length: 255 }),
  similarSpecialities: varchar("similar_specialities", { length: 1000 }),
  gender: tinyint("gender").default(1),
  docPic1: varchar("docPic1", { length: 200 }),
  docPic2: varchar("docPic2", { length: 200 }),
  docPic3: varchar("docPic3", { length: 200 }),
  docPic4: varchar("docPic4", { length: 200 }),
  docPic5: varchar("docPic5", { length: 200 }),
  timeId: varchar("timeID", { length: 255 }).default("0"),
  monday: tinyint("monday").default(0),
  tuesday: tinyint("tuesday").default(0),
  wednesday: tinyint("wednesday").default(0),
  thursday: tinyint("thursday").default(0),
  friday: tinyint("friday").default(0),
  saturday: tinyint("saturday").default(0),
  sunday: tinyint("sunday").default(0),
  startTime: varchar("startTime", { length: 100 }),
  endTime: varchar("endTime", { length: 100 }),
  onCall: tinyint("onCall").default(0),
  appointmentPhone: varchar("apptPhone", { length: 255 }),
  hospitalAssistantNumber: varchar("hospital_assistant_number", { length: 50 }),
  hospitalAdminNumber: varchar("hospital_admin_number", { length: 255 }),
  historyTime: varchar("historyTime", { length: 255 }).notNull().default("1"),
  patientsPerHour: varchar("patientsPerHour", { length: 255 }).notNull().default("6"),
  averageTimePerPatient: varchar("averageTimePerPatient", { length: 255 }).notNull().default("2"),
  appointmentMethodId: varchar("appointmentMethodID", { length: 255 }).notNull().default("2"),
  appointmentMethod: varchar("appointmentMethod", { length: 255 }).notNull().default("Automated"),
  consultationTimingType: tinyint("consultation_timing_type").notNull().default(1),
  consultationPatientType: tinyint("consultation_patient_type").notNull().default(1),
  nextSlot: tinyint("nextslot").notNull().default(0),
  hospitalId: varchar("hospitalID", { length: 255 }).default("0"),
  hospitalName: varchar("hospitalName", { length: 255 }),
  hospitalAddress: varchar("hospitalAddress", { length: 255 }),
  hospitalCity: varchar("hospitalCity", { length: 255 }).default("Lahore"),
  lat: varchar("lat", { length: 255 }),
  lng: varchar("lng", { length: 255 }),
  hospitalArea: varchar("hospitalArea", { length: 255 }),
  hospitalAreaSlug: varchar("hospital_area_slug", { length: 255 }),
  createdAt: timestamp("createdDate").notNull(),
  updatedAt: timestamp("updatedDate"),
  doctorSoundex: varchar("doctorSoundex", { length: 255 }),
  specialitySoundex: varchar("specialitySoundex", { length: 255 }),
  hospitalSoundex: varchar("hospitalSoundex", { length: 255 }),
  doctorSlug: varchar("doctorSlug", { length: 255 }).notNull(),
  degree: varchar("docDegree", { length: 500 }),
  consultancyFeeReferralOn: tinyint("consultancy_fee_referral_on").notNull().default(0),
  doctorFeeAfterHospitalShare: varchar("doctor_fee_after_hospital_share", { length: 255 }).notNull().default("0"),
  consultancyReferral: varchar("consultancy_referral", { length: 255 }).notNull().default("0"),
  contractType: tinyint("contract_type").notNull().default(1),
  similarId1: varchar("similar_id_1", { length: 255 }).notNull().default("0"),
  similarId2: varchar("similar_id_2", { length: 255 }).notNull().default("0"),
  similarId3: varchar("similar_id_3", { length: 255 }).notNull().default("0"),
  similarId4: varchar("similar_id_4", { length: 255 }).notNull().default("0"),
  similarId5: varchar("similar_id_5", { length: 255 }).notNull().default("0"),
  hospitalType: varchar("hospital_type", { length: 255 }).notNull().default("1"),
  addedByUserId: varchar("added_by_user_id", { length: 255 }).notNull().default("0"),
  updatedBy: varchar("updated_by", { length: 255 }).notNull().default("0"),
  averageWaitingTime: varchar("average_waiting_time", { length: 50 }),
  averageAppointmentTime: varchar("average_appointment_time", { length: 50 }),
  diagnosisScore: varchar("diagnosis_score", { length: 255 }).default("0"),
  staffScore: varchar("staff_score", { length: 255 }).default("0"),
  directBooking: tinyint("direct_booking").default(0),
  directBookingNotes: text("direct_booking_notes"),
  onLeave: tinyint("on_leave").default(0),
  leaveNotes: varchar("leave_notes", { length: 255 }),
  onLeaveFrom: date("on_leave_from"),
  onLeaveTo: date("on_leave_to"),
  isOnlinePaymentEnabled: tinyint("is_online_payment_enabled").default(0),
  isOnlinePaymentCompulsory: tinyint("is_online_payment_compulsory").notNull().default(0),
  ocContractedHospitalId: varchar("oc_contracted_hospital_id", { length: 255 }).notNull().default("0"),
  isScrapped: tinyint("is_scrapped").default(0),
  odooId: varchar("odoo_id", { length: 255 }),
  odooUpdatedAt: timestamp("odoo_updated_at"),
  activeAt: timestamp("active_at"),
  inactiveAt: timestamp("inactive_at"),
  isInactiveByNonPayment: tinyint("is_inactive_by_non_payment").notNull().default(0),
  deletedAt: timestamp("deleted_at"),
});
