// @ts-nocheck
import {
  mysqlTable,
  int,
  bigint,
  float,
  double,
  tinyint,
  smallint,
  boolean,
  varchar,
  text,
  longtext,
  date,
  time,
  timestamp,
  datetime,
  json,
  decimal,
} from "drizzle-orm/mysql-core";

export const doctorReviews = mysqlTable("doctor_reviews", {
  id: int("id").autoincrement().primaryKey(),
  doctorId: varchar("dID", { length: 255 }).notNull().default("0"),
  feedback: tinyint("docFeedback").notNull().default(0),
  experience: longtext("experience"),
  userId: text("userID"),
  userEmail: varchar("userEmail", { length: 255 }),
  userName: varchar("name", { length: 255 }),
  profileLink: varchar("profile_link", { length: 255 }),
  gender: varchar("gender", { length: 255 }),
  locale: varchar("locale", { length: 255 }),
  picture: varchar("picture", { length: 1000 }),
  heading: varchar("heading", { length: 1000 }),
  easyToUse: tinyint("easy_to_use").notNull().default(0),
  receivePrescription: tinyint("receive_prescription").notNull().default(0),
  isPublished: tinyint("publishedByDoctor").notNull().default(0),
  timming: tinyint("timming").notNull().default(0),
  diagnosis: tinyint("diagnosis").notNull().default(0),
  appointmentBooking: tinyint("appointment_booking").notNull().default(0),
  bookAgain: varchar("book_again", { length: 50 }),
  problem: text("problem"),
  appointmentId: bigint("appointment_id", { mode: "bigint" }).notNull().default(0),
  type: tinyint("type").notNull().default(1),
  hospitalType: tinyint("hospital_type").notNull().default(1),
  positiveFeedback: longtext("positive_feedback"),
  negativeFeedback: longtext("negative_feedback"),
  callCenterAudioUrl: varchar("call_center_audio_url", { length: 250 }),
  audioQuality: tinyint("audio_quality").default(0),
  videoQuality: tinyint("video_quality").default(0),
  consultationEndStatus: tinyint("consultation_end_status").default(0),
  doctorShowedUp: tinyint("doctor_showed_up").default(1),
  doctorBehaviour: tinyint("doctor_behaviour").default(0),
  visitedDoctor: tinyint("visited_doctor").default(0),
  recommendDoctor: tinyint("recommend_doctor").default(0),
  doctorAskedFor: varchar("doctor_asked_for", { length: 50 }),
  patientSuggestions: text("patient_suggestions"),
  city: varchar("city", { length: 50 }),
  area: varchar("area", { length: 255 }),
  waitingTime: tinyint("waiting_time").default(0),
  appointmentDuration: tinyint("appointment_duration").default(0),
  hospitalEnvironment: tinyint("hospital_environment").default(0),
  staffBehaviour: tinyint("staff_behaviour").default(0),
  satisfied: tinyint("satisfied").default(0),
  overallExperience: tinyint("overall_experience").default(0),
  recommandation: int("recommandation").default(0),
  notesForManagement: text("notes_for_management"),
  resolutionStatus: tinyint("resolution_status").default(0),
  resolutionSuggestion: text("resolution_suggestion"),
  resolutionSuggestionId: tinyint("resolution_suggestion_id").default(0),
  isPinned: tinyint("is_pinned").notNull().default(0),
  appType: tinyint("app_type").notNull().default(0),
  deviceType: tinyint("device_type").notNull().default(0),
  actions: longtext("actions"),
  reviewSentToDoctorAt: timestamp("review_sent_to_doctor_at"),
  reviewResolvedByDoctorAt: timestamp("review_resolved_by_doctor_at"),
  reviewResolvedByMarhamAt: timestamp("review_resolved_by_marham_at"),
  reviewCantBeResolvedAt: timestamp("review_cant_be_resolved_at"),
  isAnonymous: int("is_anonymous").default(0),
  approvedBy: int("approved_by"),
  unapprovedBy: int("unapproved_by"),
  deletedBy: int("deleted_by"),
  approvedAt: timestamp("approved_at"),
  unapprovedAt: timestamp("unapproved_at"),
  createdAt: timestamp("created_at").notNull(),
  updatedAt: timestamp("updated_at"),
  deletedAt: timestamp("deleted_at"),
});
