// @ts-nocheck
import {
  mysqlTable,
  int,
  bigint,
  float,
  double,
  tinyint,
  smallint,
  boolean,
  varchar,
  text,
  longtext,
  date,
  time,
  timestamp,
  datetime,
  json,
  decimal,
} from "drizzle-orm/mysql-core";

export const hospitals = mysqlTable("hospitals", {
  id: int("hospitalID").autoincrement().primaryKey(),
  name: varchar("name", { length: 500 }).notNull(),
  city: varchar("city", { length: 255 }).default("Lahore"),
  address: text("address").notNull(),
  lat: double("lat"),
  lng: double("lng"),
  area: varchar("area", { length: 255 }),
  areaSlug: varchar("area_slug", { length: 255 }),
  icu: tinyint("icu").notNull().default(1),
  emergency: tinyint("emergency").notNull().default(1),
  ventilator: tinyint("ventilator").notNull().default(1),
  phone: text("phone"),
  adminEmail: varchar("admin_email", { length: 255 }).notNull(),
  assistantEmail: varchar("assistant_email", { length: 255 }).notNull(),
  assistantNumber: varchar("assistant_number", { length: 50 }),
  adminNumber: varchar("admin_number", { length: 50 }),
  soundex: varchar("soundex", { length: 255 }).notNull(),
  timing: date("timing"),
  twentyFourHourService: tinyint("24hourservice").notNull().default(1),
  details: varchar("details", { length: 2000 }).notNull(),
  addedByUserId: varchar("addedbyuser", { length: 255 }).notNull().default("0"),
  startTime: varchar("start_time", { length: 100 }),
  endTime: varchar("end_time", { length: 100 }),
  completeAddress: varchar("complete_address", { length: 255 }),
  title: varchar("title", { length: 255 }),
  video: varchar("video", { length: 100 }),
  aboutUs: text("about_us"),
  hospitalBanner: varchar("hospitalBanner", { length: 255 }),
  hospitalPic: varchar("hospitalPic", { length: 100 }),
  hospitalPic1: varchar("hospitalPic1", { length: 100 }),
  hospitalPic2: varchar("hospitalPic2", { length: 100 }),
  hospitalPic3: varchar("hospitalPic3", { length: 100 }),
  hospitalPic4: varchar("hospitalPic4", { length: 100 }),
  hospitalPic5: varchar("hospitalPic5", { length: 100 }),
  extProfile: tinyint("ext_profile").notNull().default(0),
  extProfileCreatedAt: timestamp("ext_profile_created_at"),
  estimated: varchar("estimated", { length: 255 }).notNull().default("0"),
  slug: varchar("slug", { length: 255 }),
  shortUrl: varchar("short_url", { length: 100 }),
  code: varchar("code", { length: 50 }),
  contactEmail: varchar("contact_email", { length: 255 }),
  onlineAppointment: tinyint("online_appointment").notNull().default(0),
  lastSynced: timestamp("last_synced"),
  seoH1: varchar("seo_h1", { length: 255 }),
  seoTitle: varchar("seo_title", { length: 255 }),
  seoMetaDescription: varchar("seo_meta_description", { length: 400 }),
  seoPageDescription: longtext("seo_page_description"),
  logo: varchar("logo", { length: 255 }),
  type: varchar("type", { length: 255 }).notNull().default("1"),
  country: varchar("country", { length: 255 }).default("Pakistan"),
  branchOf: varchar("branch_of", { length: 255 }).default("0"),
  canonicalAt: varchar("canonical_at", { length: 255 }),
  verifiedAddress: varchar("verified_address", { length: 255 }),
  verifiedBy: varchar("verified_by", { length: 255 }).default("0"),
  mapUrl: varchar("map_url", { length: 50 }),
  onPanel: tinyint("on_panel").default(0),
  locationVerifiedBy: varchar("location_verified_by", { length: 255 }),
  totalShowedUps: varchar("total_showedups", { length: 255 }),
  faqs: json("faqs"),
  actions: json("actions"),
  isScrapped: tinyint("is_scrapped").default(0),
  postalCode: varchar("postal_code", { length: 255 }),
  odooId: int("odoo_id"),
  odooUpdatedAt: timestamp("odoo_updated_at"),
  verifiedAt: timestamp("verified_at"),
  onPanelAt: timestamp("on_panel_at"),
  offPanelAt: timestamp("off_panel_at"),
  locationVerifiedAt: timestamp("location_verified_at"),
  createdAt: timestamp("created_at").notNull(),
  updatedAt: timestamp("updated_at"),
});
