// @ts-nocheck
import {
  mysqlTable,
  int,
  bigint,
  float,
  double,
  tinyint,
  smallint,
  boolean,
  varchar,
  text,
  longtext,
  date,
  time,
  timestamp,
  datetime,
  json,
  decimal,
} from "drizzle-orm/mysql-core";

export const onlineConsultations = mysqlTable("online_consultations", {
  id: int("id").autoincrement().primaryKey(),
  appointmentId: bigint("appointment_id", { mode: "bigint" }).notNull(),
  appointmentDate: date("appointment_date"),
  appointmentTime: time("appointment_time"),
  userId: int("user_id").notNull().default(0),
  patientId: int("patient_id").notNull().default(0),
  patientName: varchar("patient_name", { length: 255 }),
  patientEmail: varchar("patient_email", { length: 255 }),
  patientPhone: varchar("patient_phone", { length: 255 }),
  doctorId: int("doctor_id").notNull().default(0),
  doctorName: varchar("doctor_name", { length: 255 }),
  doctorEmail: varchar("doctor_email", { length: 255 }),
  doctorPhone: varchar("doctor_phone", { length: 255 }),
  requestedSpecialityId: int("requested_speciality_id").notNull().default(0),
  problem: longtext("problem"),
  notes: longtext("notes"),
  sessionId: varchar("session_id", { length: 255 }),
  programId: int("program_id").notNull().default(0),
  paymentId: int("payment_id").notNull().default(0),
  paymentMethodId: tinyint("payment_method_id").notNull().default(0),
  paymentStatus: tinyint("payment_status").notNull().default(0),
  paymentEvidence: varchar("payment_evidence", { length: 50 }),
  paymentEvidenceMessage: text("payment_evidence_message"),
  fee: float("amount").notNull().default(0),
  appointmentStatus: int("appointment_status").notNull().default(1),
  appointmentSubStatus: int("appointment_sub_status").notNull().default(1),
  patientArrivedAt: timestamp("patient_arrived_at"),
  doctorArrivedAt: timestamp("doctor_arrived_at"),
  appType: tinyint("app_type").notNull().default(0),
  deviceType: tinyint("device_type").notNull().default(0),
  patientLastSeenAt: timestamp("patient_last_seen_at"),
  patientLiveStreamLastSeenAt: timestamp("patient_live_stream_last_seen_at"),
  doctorLastSeenAt: timestamp("doctor_last_seen_at"),
  doctorLiveStreamLastSeenAt: timestamp("doctor_live_stream_last_seen_at"),
  prescriptionSentAt: timestamp("prescription_sent_at"),
  promoCode: varchar("promo_code", { length: 50 }),
  isFree: tinyint("is_free").notNull().default(0),
  isReferred: tinyint("is_referred").notNull().default(0),
  isPromotional: tinyint("is_promotional").notNull().default(0),
  promotionalFor: bigint("promotional_for", { mode: "bigint" }).notNull().default(0),
  referredBy: int("referred_by").notNull().default(0),
  referredTo: int("referred_to").notNull().default(0),
  referredSpecialityId: int("referred_speciality_id").notNull().default(0),
  leadSourceId: int("lead_source_id").notNull().default(1),
  uuid: varchar("uuid", { length: 50 }),
  visitorSource: varchar("visitor_source", { length: 255 }),
  utmSource: varchar("utm_source", { length: 255 }),
  utmMedium: varchar("utm_medium", { length: 255 }),
  utmCampaign: varchar("utm_campaign", { length: 255 }),
  ipAddress: varchar("ip_address", { length: 50 }),
  addedBy: int("added_by").notNull().default(0),
  showedUpVia: tinyint("showed_up_via").notNull().default(0),
  isCallMyDoctor: tinyint("is_call_my_doctor").notNull().default(0),
  isRocheAppointment: tinyint("is_roche_appointment").notNull().default(0),
  rocheQuestionnaire: longtext("roche_questionnaire"),
  isObesityClinicRequest: tinyint("is_obesity_clinic_request").notNull().default(0),
  paymentPendingMarkedAt: timestamp("payment_pending_marked_at"),
  createdAt: timestamp("created_at").notNull(),
  updatedAt: timestamp("updated_at"),
  deletedAt: timestamp("deleted_at"),
});
