// @ts-nocheck
import {
  mysqlTable,
  int,
  bigint,
  float,
  double,
  tinyint,
  smallint,
  boolean,
  varchar,
  text,
  longtext,
  date,
  time,
  timestamp,
  datetime,
  json,
  decimal,
} from "drizzle-orm/mysql-core";

export const patients = mysqlTable("patients", {
  id: int("id").autoincrement().primaryKey(),
  name: varchar("patientName", { length: 255 }).notNull(),
  age: int("age"),
  gender: varchar("gender", { length: 255 }),
  symptoms: varchar("symptoms", { length: 1000 }),
  phone: varchar("phone", { length: 255 }),
  city: varchar("city", { length: 255 }),
  area: varchar("area", { length: 255 }),
  userId: int("userID"),
  bloodPressure: varchar("patient_blood_pressure", { length: 50 }),
  bloodSugar: float("patient_blood_sugar").notNull().default(0),
  height: float("patient_height").notNull().default(0),
  weight: float("patient_weight").notNull().default(0),
  medicalHistory: varchar("patient_medical_history", { length: 1000 }),
  familyMedicalHistory: varchar("patient_family_medical_history", { length: 1000 }),
  surgeries: varchar("patient_surgeries", { length: 1000 }),
  medications: varchar("patient_medications", { length: 1000 }),
  conditions: varchar("patient_conditions", { length: 1000 }),
  temperature: varchar("patient_temperature", { length: 100 }),
  heartRate: varchar("patient_heart_rate", { length: 100 }),
  spo2: varchar("patient_spo2", { length: 100 }),
  pefr: varchar("patient_pefr", { length: 100 }),
  ent: varchar("patient_ent", { length: 100 }),
  chest: varchar("patient_chest", { length: 100 }),
  address: varchar("patient_address", { length: 100 }),
  occupation: varchar("patient_occupation", { length: 50 }),
  disease: varchar("disease", { length: 255 }),
  techSavy: tinyint("tech_savy").notNull().default(0),
  bmi: varchar("bmi", { length: 255 }),
  preferredWayOfWeightloss: varchar("preferred_way_of_weightloss", { length: 255 }),
  desiredWeightLoss: varchar("desired_weight_loss", { length: 255 }),
  timeToLoseWeight: varchar("time_to_lose_weight", { length: 255 }),
  maritalStatus: varchar("marital_status", { length: 255 }),
  personalHistory: longtext("personal_history"),
  systematicHistory: longtext("systematic_history"),
  surgicalHistory: longtext("surgical_history"),
  gyneAndObsHistory: longtext("gyne_and_obs_history"),
  weightlossOptionsTriedInPast: varchar("weightloss_options_tried_in_past", { length: 255 }),
  weightlossOptionsTriedInPastOther: longtext("weightloss_options_tried_in_past_other"),
  everAllergicToMedications: tinyint("ever_allergic_to_medications"),
  everAllergicToMedicationsOther: longtext("ever_allergic_to_medications_other"),
  forWhichYouStruggle: varchar("for_which_you_struggle", { length: 255 }),
  forWhichYouStruggleOther: longtext("for_which_you_struggle_other"),
  interestedInMedications: tinyint("interested_in_medications"),
  interestedInMedicationsOther: longtext("interested_in_medications_other"),
  uuid: varchar("uuid", { length: 50 }),
  visitorSource: varchar("visitor_source", { length: 50 }),
  utmSource: varchar("utm_source", { length: 255 }),
  utmMedium: varchar("utm_medium", { length: 255 }),
  utmCampaign: varchar("utm_campaign", { length: 255 }),
  createdAt: timestamp("created_at").notNull(),
  updatedAt: timestamp("updated_at"),
});
