// @ts-nocheck
import {
  mysqlTable,
  int,
  bigint,
  float,
  double,
  tinyint,
  smallint,
  boolean,
  varchar,
  text,
  longtext,
  date,
  time,
  timestamp,
  datetime,
  json,
  decimal,
} from "drizzle-orm/mysql-core";

export const specialities = mysqlTable("specialities", {
  id: int("spID").autoincrement().primaryKey(),
  name: varchar("speciality", { length: 255 }),
  image: varchar("speciality_image", { length: 255 }),
  title: varchar("title", { length: 255 }),
  title2: varchar("title_2", { length: 255 }),
  slug: varchar("slug", { length: 255 }),
  detail: varchar("detail", { length: 255 }),
  causes: varchar("causes", { length: 255 }),
  specialitySoundex: varchar("specialitySoundex", { length: 255 }),
  urduName: varchar("urdu_name", { length: 1000 }),
  parent: varchar("parent", { length: 255 }).notNull().default("0"),
  parentSlug: varchar("parent_slug", { length: 255 }),
  seoH1: varchar("seo_h1", { length: 255 }),
  seoH2: varchar("seo_h2", { length: 255 }),
  seoTitle: varchar("seo_title", { length: 255 }),
  seoMetaDescription: varchar("seo_meta_description", { length: 500 }),
  seoPageDescription: text("seo_page_description"),
  seoKeywords: varchar("seo_keywords", { length: 255 }),
  onlineConsultationVideo: varchar("online_consultation_video", { length: 255 }),
  position: varchar("position", { length: 255 }).default("100"),
  redirectTo: varchar("redirect_to", { length: 255 }),
  faqs: longtext("faqs"),
  actions: json("actions"),
  algoStatus: tinyint("algo_status").notNull().default(0),
  algoUpdatedAt: datetime("algo_updated_at"),
  algoUpdatedBy: varchar("algo_updated_by", { length: 255 }),
  seoContent: json("seo_content"),
  aboutUsContent: longtext("about_us_content").notNull(),
  bannerInfo: json("banner_info"),
  isScrapped: tinyint("is_scrapped").default(0),
  createdAt: timestamp("created_at"),
  updatedAt: timestamp("updated_at"),
});
