// @ts-nocheck
import {
  mysqlTable,
  int,
  bigint,
  float,
  double,
  tinyint,
  smallint,
  boolean,
  varchar,
  text,
  longtext,
  date,
  time,
  timestamp,
  datetime,
  json,
  decimal,
} from "drizzle-orm/mysql-core";

export const users = mysqlTable("users", {
  id: int("id").autoincrement().primaryKey(),
  socialUserId: varchar("socialUserID", { length: 255 }),
  doctorId: varchar("dID", { length: 255 }).notNull().default("0"),
  email: varchar("email", { length: 255 }),
  name: varchar("name", { length: 255 }),
  username: varchar("username", { length: 255 }),
  password: varchar("password", { length: 255 }),
  passwordText: varchar("password_text", { length: 255 }),
  fName: varchar("FName", { length: 255 }),
  lName: varchar("LName", { length: 255 }),
  phone: varchar("phone", { length: 255 }),
  isDoctor: tinyint("isDoctor").notNull().default(0),
  isAssistant: tinyint("isAssistant").notNull().default(0),
  isHospitalAssistant: tinyint("is_hospital_assistant").notNull().default(0),
  isHospitalAdmin: tinyint("is_hospital_admin").notNull().default(0),
  canComment: tinyint("canComment").notNull().default(1),
  approved: tinyint("approved").notNull().default(1),
  request: varchar("request", { length: 255 }),
  schedular: tinyint("schedular").notNull().default(0),
  schedularSettingsChanged: tinyint("schedularsettingschanged").notNull().default(0),
  wizardCompleted: tinyint("wizardcompleted").notNull().default(0),
  rememberToken: varchar("remember_token", { length: 100 }),
  firstLogin: varchar("firstLogin", { length: 255 }).notNull().default("1"),
  verified: tinyint("verified").notNull().default(0),
  notification: tinyint("notification").notNull().default(1),
  extProfile: tinyint("extprofile").notNull().default(0),
  avatar: varchar("avatar", { length: 1000 }),
  dToken: varchar("_dtoken", { length: 255 }),
  isEmailUnsubscribe: tinyint("is_email_unsubscribe").notNull().default(0),
  emr: tinyint("emr").notNull().default(0),
  usersEmrSteps: tinyint("users_emr_steps").notNull().default(0),
  userWeightLossProgram: tinyint("user_weight_loss_program").notNull().default(0),
  specialDiscount: varchar("special_discount", { length: 255 }).notNull().default("0"),
  type: varchar("type", { length: 255 }).notNull().default("10"),
  updatedBy: varchar("updated_by", { length: 255 }).notNull().default("0"),
  gender: varchar("gender", { length: 255 }),
  maritalStatus: varchar("marital_status", { length: 255 }),
  dateOfBirth: date("date_of_birth"),
  accessToken: varchar("access_token", { length: 50 }),
  rights: longtext("rights"),
  wallet: longtext("wallet"),
  easypaisaOpenId: varchar("easypaisa_open_id", { length: 255 }),
  cnic: varchar("cnic", { length: 255 }),
  extProfileCreatedAt: timestamp("ext_profile_created_at"),
  createdAt: timestamp("created_at").notNull(),
  updatedAt: timestamp("updated_at"),
});
